CREATE TABLE users(
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		email VARCHAR(255) NOT NULL,
		password VARCHAR(255) NOT NULL,
		role VARCHAR(6),
		created_at TIMESTAMP,
		updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	);