CREATE TABLE products(
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		description VARCHAR(255),
		price DECIMAL(15,2) DEFAULT 0 NOT NULL,
		ratingA DECIMAL(2,1) DEFAULT 0.0 NOT NULL,
		users_id BIGINT,
		created_at TIMESTAMP,
		updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		FOREIGN KEY(users_id) REFERENCES users(id) ON DELETE CASCADE
);