CREATE TABLE products(
		id BIGINT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		description VARCHAR(255),
		price DECIMAL(15,2) DEFAULT 0 NOT NULL,
		ratingA DECIMAL(2,1) DEFAULT 0.0 NOT NULL,
		users_id BIGINT,
		category_id BIGINT,
		brands_id BIGINT,
		images_id BIGINT,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		FOREIGN KEY(users_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY (category_id) REFERENCES categories(id),
		FOREIGN KEY (brands_id) REFERENCES brands(id),
		FOREIGN KEY (images_id) REFERENCES images(id)
);